export const genreMapping: Record<string, string> = {
   "action": "Action",
   "adventure": "Adventure",
   "animation": "Animation",
   "comedy": "Comedy",
   "crime": "Crime",
   "documentary": "Documentary",
   "drama": "Drama",
   "family": "Family",
   "fantasy": "Fantasy",
   "history": "History",
   "horror": "Horror",
   "music": "Music",
   "mystery": "Mystery",
   "romance": "Romance",
   "sci-fi": "Science Fiction",
   "tv-movie": "TV Movie",
   "thriller": "Thriller",
   "war": "War",
   "western": "Western",
};

